# Start from golang base image
FROM golang:1.18

# Add Maintainer info
LABEL maintainer="Kevin Li"

ARG NOTIFIER_PORT

ENV GOPATH="$HOME/go"
ENV PATH="$GOPATH:$PATH" 

# Setup folders
WORKDIR /app

# Copy the source from the current directory to the working Directory inside the container
COPY . .
COPY .env .

WORKDIR /app/notifier-service
# Download all the dependencies
RUN go mod download
RUN go get -d -v ./...
RUN go install -v ./...

EXPOSE ${NOTIFIER_PORT}

CMD ["go", "run", "main.go"]