# Start from golang base image
FROM golang:1.18

# Add Maintainer info
LABEL maintainer="Kevin Li"

ARG API_PORT

ENV GOPATH="$HOME/go"
ENV PATH="$GOPATH:$PATH" 

# Setup folders
WORKDIR /app

# Copy the source from the current directory to the working Directory inside the container
COPY . .
COPY .env .

RUN rm -rf client/

WORKDIR /app/go-place
# Download all the dependencies
RUN go mod download
RUN go get -d -v ./...
RUN go install -v ./...

EXPOSE ${API_PORT}

CMD ["./wait-for-it.sh", "cassandraboard:9042", "-t", "90", "--", "make", "app/dev"]